version: '3'

services:
  postgres:
    image: postgres:13
    # ports:
    #   - "5432:5432"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - "PGADMIN_DEFAULT_EMAIL=user@dwws.ufes.br"
      - PGADMIN_DEFAULT_PASSWORD=1234

  wildfly:
    image: dwws/wildfly:24.0.1-preview
    ports:
      - "9990:9990"
      - "8080:8080"
    environment:
      - TZ
    depends_on:
      - postgres

volumes:
  postgres-data:
